### ISSUE TITLE
KeyError: '__array_struct__' on StructArray creation

### ISSUE THREAD

**Issue by johmedr** [spm/spm-python#13]
```python
S = Struct()
S.data = op.join(datapath, 'OPM_meg_001.cMEG')
S.positions = op.join(datapath, 'OPM_HelmConfig.tsv')
D = spm_opm_create(S)
```
raises
 ```python
KeyError: '__array_struct__'
```

**Comment by johmedr** [comment]
This comes from a missing `__array__` method on the `Struct` class. Numpy calls `__getattr__` that triggers `dict.__getitem__`, raising the `KeyError`. 

The fix is to make the `Struct` class less permissive: attribute starting with `__` now raise an AttributeError.

**Comment by arthurmitchell96** [comment]
Hey Johan I am still getting this issue after standard install, please advise on a fix

**Comment by johmedr** [comment]
Hey Arthur, I think this is because it was fixed on the code but not propagated to Pip.
Can you retry after `pip install -U spm-python`?

**Comment by arthurmitchell96** [comment]
I still get some warnings but it now seems to work, thank you.
Warnings are:
"
In mpython_endpoint (line 18)
Data type is missing or incorrect, assigning default.
Warning: amplitude, distance and scaling are not supported for version "2011v2"
"

**Comment by johmedr** [comment]
Nice, good to know 👍 
The warning you mention is from SPM, you should have the same in Matlab!
